### ISSUE TITLE
My keyboard will lost after i switched a conversation in a real mobile device 

### ISSUE THREAD

**Issue by nobodyhi** [talkjs/talkjs-react#1]
I build a conversation list with RESTAPI, it works well on a  browser of my computer, but on a real mobile device not.
it was working when i entered the first chat, when i went back to change chat, from then on it didn't work.
Here's my screen [recording.](https://static.myfactoryguy.com/issues/lostkeyboard.MP4)

**Comment by Asha20** [comment]
Hey @nobodyhi, since you mentioned this in live support as well and we handled it there I'm going to close this issue for now. If the problem re-appears or you run into another one, please don't hesitate to reach out via live support or open a new issue here on Github.
