### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

### ISSUE THREAD

**Issue by enlguy** [talkjs/talkjs-react#14]
This is from the TalkJS sample repo.  I downloaded directly from GitHub, ran npm i, added the AppID, and then ran the app in dev mode.  Won't load.  Throws the error mentioned, and elaborated below.  

This comes after already having to downgrade React to v16 because TalkJS throws dep errors with newer versions.  Is TalkJS completely depracated?

```
Unhandled Runtime Error

TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')

Call Stack
ReactCurrentDispatcher
node_modules\@talkjs\react\dist\talkjs-react.js (220:16)
Mr
node_modules\@talkjs\react\dist\talkjs-react.js (651:3)
Mr
node_modules\@talkjs\react\dist\talkjs-react.js (653:74)
./node_modules/@talkjs/react/dist/talkjs-react.js
file:///D:/GitHub/talkjstest/.next/static/chunks/app/page.js (72:1)
Next.js
options.factory
file:///D:/GitHub/talkjstest/.next/static/chunks/webpack.js (712:31)
__webpack_require__
file:///D:/GitHub/talkjstest/.next/static/chunks/webpack.js (37:33)
fn
file:///D:/GitHub/talkjstest/.next/static/chunks/webpack.js (369:21)
eval
./app/page.js
./app/page.js
file:///D:/GitHub/talkjstest/.next/static/chunks/app/page.js (39:1)
Next.js
options.factory
file:///D:/GitHub/talkjstest/.next/static/chunks/webpack.js (712:31)
__webpack_require__
file:///D:/GitHub/talkjstest/.next/static/chunks/webpack.js (37:33)
fn
file:///D:/GitHub/talkjstest/.next/static/chunks/webpack.js (369:21)
requireModule
./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js
initializeModuleChunk
./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js
resolveModuleChunk
./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js
eval
./node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-client.browser.development.js
```

**Comment by frederikcreemers** [comment]
Hi there,

Thank you for reaching out to us. Sorry to hear you're having these issues getting TalkJS up and running in your React project. I see you've also reached out to us via our support chat. We'll continue the conversation there to try and resolve the problem, and then update this issue once that's done.

**Comment by KlotzJesse** [comment]
@frederikcreemers 

Can be fixed by correctly not-bundling react in the vite.config.ts
line 33:
` external: ['react', 'talkjs'],`

to

`external: ["react", /^react\/.*/, "react-dom", /react-dom\/.*/, 'talkjs'],`

**Comment by keerlu** [comment]
Closing this issue as the original problem has now been solved over live support – it related to only downloading some files from the example and running into dependency issues. This was resolved by using the versions in our package.json file.

We’ve also now added links to all our example READMEs to make it easier to download the example you need without needing to clone the whole repo.

@KlotzJesse we’d still love to get some more context about your suggestion – please feel free to open a new issue if you’ve run into a similar problem.

**Comment by keerlu** [comment]
Closing this issue as the original problem has now been solved over live support – it related to only downloading some files from the example and running into dependency issues. This was resolved by using the versions in our package.json file.

We’ve also now added links to all our example READMEs to make it easier to download the example you need without needing to clone the whole repo.

@KlotzJesse we’d still love to get some more context about your suggestion – please feel free to open a new issue if you’ve run into a similar problem.
